### PR TITLE
Code Review for React Redux Capstone Project

### PR DESCRIPTION
**Pull request by luigirazum**
# Hello Dear Code Reviewers Team 👋,
#### - 🎯 General requirements
- 📌 Make sure that there are no linter errors.
  - ✅ Linters for React Redux were installed. No errors.
- 📌 Make sure that you used correct git-flow.
  - ✅ `dev` branch was created and made default branch.
  - ✅ Branches were created from `dev` to follow the `git-flow`.
  - ✅ This Pull Request is made from `dev` to `main` to FOLLOW the `git-flow`.
- 📌 Make sure that you documented your work in a professional way.
  - ✅ The `README` file was added with details about the project.
  - ✅ The presentation video is available through [this link](https://screenrec.com/share/9S0LF3QTRU)
#### - 🎯 Project requirements
- ✅ An API about cryptocurrencies was chosen to develop the project.
- ✅ Implemented React/Redux.
- ✅ A general listing for the Cryptocurrencies is shown by pressing START.
- ✅ Clicking a Coin from the list, will take you to the details page for that coin.
- ✅ The < back button will take you to the whole list.
- ✅ The list can be filtered typing the name or the symbol name for a cryptocurrency.
- ✅ You can clear the filter pressing the X button right at the filter field.
- ✅ Added tests using React Testing Library.
- ✅ Added basic styles with colors and fonts from the suggested guidelines.
- ✅ Deployed the project at netlify. Live demo available.
- ✅ Added a README with the details of the project.

### Luis 🙋‍♂️

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi AnLuis, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that capstone project worked on by a single contributor should have Pull Request flow **from feature into development**. Kindly use the correct gitflow and request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by luigirazum** [comment]
But I did follow the gitflow...

**Review by rotimiazeez — APPROVED** [review]
Hi @luigirazum 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job presenting your project 👍🏽 (It would have been great if you highlight and explain a piece of your code that you are proud of)
- Good App UI 🖼️
- Project uses `Redux` for state management and data retrieved from the `API` are stored in the Redux store correctly. 👏🏽
- App functioning as required 😉
- App deployed 💯
- No linter error ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luigirazum** [comment]
Thanks @rotimiazeez, but I can't submit the project, the platform is closed. 😭

**Pull request merged**
